### ISSUE TITLE
convert repo to a template 

### ISSUE THREAD

**Issue by SreehariJayaraj** [fadhilsaheer/fadhilsaheer.github.io#2]
hey, @fadhilsaheer  first of all the website looks dope! can you convert this repo to a template, i am really interested in changing my [personal site](https://www.sreeharijayaraj.me/) to your design can you  create a template ?

**Comment by fadhilsaheer** [comment]
Yeah sure, the code is easy to understand so you can customize it however you want 🎨
> In order to customize certain part please edit these files

|  Path  | Function  |
|---|---|
| `/index.html` | Customize SEO options like page title, icon, banner & meta tags |
| `/src/data/projects.ts` | Projects are exported as JS array, each item is an object with type interface `Project` (which will include title, description, stack & link to project) | 
| `/src/data/skills.ts` | Skills are exported as JS array, each item is an object with type interface `SkillType` (which will include title, icon & link) |
| `/src/components/About.ts` | Customize about section of the page |
| `/src/components/Experience.ts` | Customize experience section of the page, there is a custom component named `ExperienceObject` which will take name, time, website, image & job as props to display roles/position in different companies |
| `/src/components/Footer.ts` | Customize links to socials |
| `/src/components/ProfileImage.ts` | Customize image |
| `/src/components/Socials.ts` | Customize main social icons, which will be shown in header & below about section |
